name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  check-code:
    runs-on: ubuntu-latest
    if: secrets.BUCKET != ''
    steps:
      - name: Use secret
        run: echo "Using secret value"
#    defaults:
#      run:
#        shell: bash
#        working-directory: ./terra_cluster
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: ${{ secrets.TERRAFORM_VERSION }}
#      - name: Terraform Init
#        id: init
#        env:
#          BUCKET: ${{ secrets.BUCKET }}
#          ACCESS_KET: ${{ secrets.ACCESS_KEY }}
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
#        run: terraform init -backend-config="bucket=$BUCKET" -backend-config="access_key=$ACCESS_KET" -backend-config="secret_key=$SECRET_KEY"
      # - name: Terraform Plan
      #   run: terraform plan
      #   env:
      #     TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
      #     TF_VAR_token: ${{ secrets.TF_VAR_TOKEN }}
      #     TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
      #     TF_VAR_remoute_ssh_pub: ${{ secrets.SSH_PUB_INSTANCE }}
