name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  check-code:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./terra_cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Terraform Init
        id: init
        env:
          BUCKET: ${{ BUCKET }}
          ACCESS_KET: ${{ ACCESS_KEY }}
          SECRET_KEY: ${{ SECRET_KEY }}
        run: terraform init -backend-config="bucket=$BUCKET" -backend-config="access_key=$ACCESS_KET" -backend-config="secret_key=$SECRET_KEY"
